### PR TITLE
Task: add resilient model types

### PR DESCRIPTION
**Pull request by craigamcw**
Task: Add text to Elaborate on "Choose a model type resilient against a transfer learning attack"

### CODE REVIEW

**Review by robvanderveer — CHANGES_REQUESTED** [review]
Thank you. Transfer learning attacks are about using a vulnerable pre-trained model for fine-tuning. It is development-time model poisoning through supply chain. Your suggested text is more about robustness agains adversarial examples, which is covered elsewhere in the documents.

**Comment by craigamcw** [comment]
Thank you. More appropriate would be to; Choose a model type that incorporates defensive mechanisms such as adversarial training, regularization, or ensemble techniques, which can enhance the model's resilience to transfer learning attacks.

**Comment by robvanderveer** [comment]
we have these as controls (ensemble, adversarial training). Any suggestions?

**Comment by craigamcw** [comment]
I will cancel the PR and revise with some suggestions.

**Pull request closed without merging**
